/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-29 16:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1652317442487L));
    _jspx_dependants.put("jar:file:/D:/eclipse/vemaybay/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/vemaybay/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LUDAirLine</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/detail.css\">\r\n");
      out.write("    <script language=\"javascript\">\r\n");
      out.write("        document.getElementById(\"btn1\").onclick = function () {\r\n");
      out.write("            document.getElementById(\"content\").style.display = 'block';\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\" jss8\">\r\n");
      out.write("        <div class=\"MuiBox-root jss13 jss9\" id=\"id-header-wrapper-content-listing\" >\r\n");
      out.write("        <div class=\"jss3820\">\r\n");
      out.write("           <header class=\"header\">\r\n");
      out.write("            <div class=\"header-body\">\r\n");
      out.write("                    <div class=\"body-items\">\r\n");
      out.write("                        <a class=\"header-body-logo\" href=\"index.jsp\">\r\n");
      out.write("                            <i class=\"fa-solid fa-paper-plane\">LUD TICKETS</i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"header-body-items\" >\r\n");
      out.write("                            <div class=\"header-body-items1\">\r\n");
      out.write("                                <svg width=\"15\" heigth=\"15\" viewbox=\"0 0 15 15\" fill=\"none\" class=\"item\"></svg>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <span class=\"span1\">|</span>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"header-body-items2\">\r\n");
      out.write("                               \r\n");
      out.write("                             <div class=\"header-body-items2\">\r\n");
      out.write("                            <ul class=\"items\">\r\n");
      out.write("                             ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <li class=\"item1\">\r\n");
      out.write("                                <a href=\"\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"jss2636\">Check in online</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>       \r\n");
      out.write("                            </div>            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header> --> \r\n");
      out.write("            <div class=\"MuiBox-root jss90\" style=\"width:100%\">\r\n");
      out.write("                <div class=\"MuiBox-root jss91 jss71\">\r\n");
      out.write("                    <form action=\"searchcontrol1\" method=\"get\">\r\n");
      out.write("                        <div class=\"MuiBox-root jss92 jss75\" style=\"border:none;margin-top:0;box-shadow:0px 15px 15px rgba(0, 0, 0, 0.2)\">\r\n");
      out.write("                            <div class=\"MuiBox-root jss93 jss80\">\r\n");
      out.write("                                <div class=\"MuiBox-root jss94 jss83\">\r\n");
      out.write("                                    <div class=\"MuiBox-root jss95 jss78\">Từ</div>\r\n");
      out.write("                                    <div class=\"select\">\r\n");
      out.write("                                        <select name=\"sbdi\" style=\"height: 25px; width: 200px; font-size: larger; font-weight: 700;\">\r\n");
      out.write("                                          <option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbaydi.masb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbaydi.tentp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("                                             <option value=\"SGN\">TP.Hồ Chí Minh</option>\r\n");
      out.write("                                                      <option value=\"HAN\">Hà Nội</option>\r\n");
      out.write("                                                      <option value=\"BMV\">Buôn Ma Thuột</option>\r\n");
      out.write("                                                      <option value=\"VCA\">Cần Thơ</option>\r\n");
      out.write("                                                      <option value=\"DAD\">Đà Nẵng</option>\r\n");
      out.write("                                                      <option value=\"DLI\">Đà Lạt</option>\r\n");
      out.write("                                                      <option value=\"VII\">TP.Vinh</option>\r\n");
      out.write("                                                      <option value=\"PQC\">Kiên Giang</option>\r\n");
      out.write("                                                      <option value=\"CXR\">Nha Trang</option>\r\n");
      out.write("                                                      <option value=\"UIH\">Bình Định</option>\r\n");
      out.write("                                                      <option value=\"VCS\">Bà Rịa-Vũng Tàu</option>\r\n");
      out.write("                                                      <option value=\"HUI\">Huế</option>\r\n");
      out.write("                                                      <option value=\"VDH\">Quảng Bình</option>\r\n");
      out.write("                                                      <option value=\"TBB\">Phú Yên</option>\r\n");
      out.write("                                                      <option value=\"HPH\">Hải Phòng</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div> \r\n");
      out.write("                                  \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"MuiBox-root jss98 jss81\">\r\n");
      out.write("                                    <div class=\"MuiBox-root jss99 jss83 \">\r\n");
      out.write("                                        <div class=\"MuiBox-root jss100 jss78\">Đến</div>\r\n");
      out.write("                                       <div class=\"select\" >\r\n");
      out.write("                                            <select name=\"sbden\" style=\"height: 25px;width: 200px;font-size: larger;font-weight: 700;\">\r\n");
      out.write("                                              <option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbayden.masb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbayden.tentp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>                           \r\n");
      out.write("                                                <option value=\"SGN\">TP.Hồ Chí Minh</option>\r\n");
      out.write("                                                      <option value=\"HAN\">Hà Nội</option>\r\n");
      out.write("                                                      <option value=\"BMV\">Buôn Ma Thuột</option>\r\n");
      out.write("                                                      <option value=\"VCA\">Cần Thơ</option>\r\n");
      out.write("                                                      <option value=\"DAD\">Đà Nẵng</option>\r\n");
      out.write("                                                      <option value=\"DLI\">Đà Lạt</option>\r\n");
      out.write("                                                      <option value=\"VII\">TP.Vinh</option>\r\n");
      out.write("                                                      <option value=\"PQC\">Kiêng Giang</option>\r\n");
      out.write("                                                      <option value=\"CXR\">Nha Trang</option>\r\n");
      out.write("                                                      <option value=\"UIH\">Bình Định</option>\r\n");
      out.write("                                                      <option value=\"VCS\">Bà Rịa-Vũng Tàu</option>\r\n");
      out.write("                                                      <option value=\"HUI\">Huế</option>\r\n");
      out.write("                                                      <option value=\"VDH\">Quảng Bình</option>\r\n");
      out.write("                                                      <option value=\"TBB\">Phú Yên</option>\r\n");
      out.write("                                                      <option value=\"HPH\">Hải Phòng</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                          </div> \r\n");
      out.write("                                       \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"MuiBox-root jss102 jss81\">\r\n");
      out.write("                                    <div class=\"MuiBox-root jss103\" style=\"margin-left:24px;position:relative;min-width:275px\">\r\n");
      out.write("                                        <div class=\"MuiBox-root jss104 jss78\">Ngày đi \r\n");
      out.write("                                            <div class=\"jss82\" style=\"background:transparent\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.chuyenbay.ngaydi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"name=\"ngaydi\" type=\"date\" style=\"font-weight: 700;height: 25px; width: 200px;\">                                                   \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"MuiBox-root jss114 jss81\">\r\n");
      out.write("                                    <div class=\"MuiBox-root jss115\" style=\"margin-left:24px;position:relative\">\r\n");
      out.write("                                        <div class=\"MuiBox-root jss116 jss83\">\r\n");
      out.write("                                            <div class=\"MuiBox-root jss117 jss78\">Hãng bay</div>\r\n");
      out.write("                                            <div class=\"select\" >\r\n");
      out.write("                                                <select name=\"hangbay\" style=\"\r\n");
      out.write("                                                height: 25px;\r\n");
      out.write("                                                width: 200px;\r\n");
      out.write("                                                \r\n");
      out.write("                                                font-size: larger;\r\n");
      out.write("                                                font-weight: 700;\r\n");
      out.write("                                            \">\r\n");
      out.write("                                                  <option value=\"Vietnam Airlines\" selected disabled>Hãng bay</option>\r\n");
      out.write("                                                  <option value=\"Vietnam Airlines\">Vietnam Airlines</option>\r\n");
      out.write("                                                  <option value=\"Bamboo Airways\">Bamboo Airway</option>\r\n");
      out.write("                                                  <option value=\"Pacific Airlines\">Pacific Airlines</option>\r\n");
      out.write("                                                  <option value=\"Vietjet Air\">Vietjet Air</option>\r\n");
      out.write("                                                 \r\n");
      out.write("                                                </select>\r\n");
      out.write("                                              </div> \r\n");
      out.write("                                            <div class=\"jss82\" style=\"background:transparent\"></div>\r\n");
      out.write("                                        </div>                                       \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button class=\" jssbutton MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary  \" tabindex=\"0\" type=\"submit\" style=\"width: 100px; height: 56px; cursor: pointer; border-radius: 8px; box-shadow: none;\">\r\n");
      out.write("                                    <span class=\"MuiButton-label\">\r\n");
      out.write("                                        <svg width=\"23\" height=\"24\" fill=\"none\" class=\"svgFillAll\" style=\"stroke:white\">\r\n");
      out.write("                                            <path d=\"M21.312 22.5l-4.742-4.742m2.71-7.451a8.806 8.806 0 11-17.613 0 8.806 8.806 0 0117.613 0z\" stroke=\"#fff\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"MuiTouchRipple-root\"></span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <main>\r\n");
      out.write("            <div class=\"MuiBox-root jss119 jss2\" id=\"idHomeWrapper\">\r\n");
      out.write("                <div class=\"MuiBox-root jss120 jss3\">\r\n");
      out.write("                    <div class=\"MuiBox-root jss121 jss4\">\r\n");
      out.write("                        <div class=\"MuiBox-root jss122\" style=\"width:100%;padding-top:24px;margin-left:auto;padding-left:0\">\r\n");
      out.write("                            <div class=\"MuiBox-root jss123 jss6\">\r\n");
      out.write("                                <div class=\"MuiBox-root jss124 jss7\">\r\n");
      out.write("                                    <div class=\"MuiBox-root jss136\">\r\n");
      out.write("                                        <nav class=\"MuiTypography-root MuiBreadcrumbs-root MuiTypography-body1 MuiTypography-colorTextSecondary\" style=\"margin-bottom:16px;color:#4A5568\">\r\n");
      out.write("                                            <ol class=\"MuiBreadcrumbs-ol\">\r\n");
      out.write("                                                <li class=\"MuiBreadcrumbs-li\">\r\n");
      out.write("                                                    <a class=\"MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorInherit\" href=\"\">\r\n");
      out.write("                                                        <p class=\"MuiTypography-root MuiTypography-body2\">Vé máy bay</p>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li aria-hidden=\"true\" class=\"MuiBreadcrumbs-separator\">›</li>\r\n");
      out.write("                                                <li class=\"MuiBreadcrumbs-li\">\r\n");
      out.write("                                                    <a class=\"MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorInherit\" href=\"\">\r\n");
      out.write("                                                        <p class=\"MuiTypography-root MuiTypography-body2\">Chuyến bay từ<!-- --> <!-- -->");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbaydi.tentp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<!-- --> <!-- -->đến<!-- --> <!-- -->");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbayden.tentp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ol>\r\n");
      out.write("                                        </nav>\r\n");
      out.write("                                        <div class=\"MuiBox-root jss140 jss137\">\r\n");
      out.write("                                            <div class=\"MuiBox-root jss141\">\r\n");
      out.write("                                                <a class=\"MuiTypography-root MuiLink-root MuiLink-underlineHover jss138 MuiTypography-colorPrimary\" href=\"\">\r\n");
      out.write("                                                    <div class=\"MuiBox-root jss142\">\r\n");
      out.write("                                                        <p class=\"MuiTypography-root MuiTypography-body1\" style=\"font-size:24px;font-weight:600;display:flex\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbaydi.tensb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<!-- --> (<!-- -->");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbaydi.masb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<!-- -->) &nbsp;\r\n");
      out.write("                                                            <svg width=\"16\" height=\"17\" fill=\"none\">\r\n");
      out.write("                                                                <path d=\"M3.333 8.5h9.334M10 11.167L12.667 8.5M10 5.833L12.667 8.5\" stroke=\"#1A202C\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\r\n");
      out.write("                                                            </svg>\r\n");
      out.write("                                                            &nbsp;<!-- -->");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbayden.tensb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<!-- --> (<!-- -->");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sanbayden.masb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<!-- -->)\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                        <h4 class=\"MuiTypography-root MuiTypography-h4\" style=\"font-weight:400\"></h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"MuiBox-root jss143\" style=\"color:#1A202C\">\r\n");
      out.write("                                                <span class=\"MuiTypography-root MuiTypography-caption\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.chuyenbay.ngaydi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                                                <svg width=\"3\" height=\"3\" fill=\"none\" class=\"jss139\">\r\n");
      out.write("                                                    <rect width=\"3\" height=\"3\" rx=\"1.5\" fill=\"#A0AEC0\"></rect>\r\n");
      out.write("                                                </svg>\r\n");
      out.write("                                                <span class=\"MuiTypography-root MuiTypography-caption\">1<!-- -->&nbsp;<!-- -->khách</span>\r\n");
      out.write("                                                <span class=\"MuiTypography-root MuiTypography-caption\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"MuiBox-root jss144 jss5\">\r\n");
      out.write("                              ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "boloc.jsp", out, false);
      out.write("\r\n");
      out.write("                                <div class=\"MuiBox-root jss183\">\r\n");
      out.write("                                    <div class=\"MuiBox-root jss208 jss196\">\r\n");
      out.write("                                        <div class=\"MuiBox-root jss209 jss197\" id=\"banner_listing\"></div>\r\n");
      out.write("                                        <div class=\"MuiBox-root jss210 jss198\">                                                \r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <div class=\"MuiBox-root jss374 jss370\">\r\n");
      out.write("                                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("      \r\n");
      out.write("                                                 </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>            \r\n");
      out.write("        </main>\r\n");
      out.write("             ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </div>    \r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /detail.jsp(33,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                \r\n");
          out.write("                                <span class=\"span1\">\r\n");
          out.write("                                    <a class=\"login\" href=\"\">Đăng ký</a>\r\n");
          out.write("                                </span>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /detail.jsp(40,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <span class=\"span1\">\r\n");
          out.write("                                \r\n");
          out.write("                                    <a class=\"login\" href=\"login.jsp\">Đăng nhập</a>\r\n");
          out.write("                                    </span>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /detail.jsp(46,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <span class=\"span1\">\r\n");
          out.write("                                \r\n");
          out.write("                                    <a class=\"login\" href=\"dangxuatcontrol\">Đăng xuất</a>\r\n");
          out.write("                                    </span>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /detail.jsp(57,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"item1\">\r\n");
          out.write("                                <a href=\"vemaybaycontrol1?sdt=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.sdt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"jss2636\">Chuyến bay của tôi</a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /detail.jsp(232,52) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/detail.jsp(232,52) '${listchuyenbay}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listchuyenbay}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /detail.jsp(232,52) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                                        <div class=\"MuiBox-root jss375 jss373\">\r\n");
            out.write("                                                            <div class=\"MuiBox-root jss376\">\r\n");
            out.write("                                                                <div class=\"MuiBox-root jss402 jss377\" style=\"border-radius: 8px;\">\r\n");
            out.write("                                                                    <div class=\"MuiBox-root jss403 jss380\">\r\n");
            out.write("                                                                        <div class=\"MuiBox-root jss404 jss386\">\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss405\">\r\n");
            out.write("                                                                                <div class=\"MuiBox-root jss406\">\r\n");
            out.write("                                                                                    <div class=\"jss291 jss387\">\r\n");
            out.write("                                                                                        <div class=\"jss292 jss295\" style=\"border-radius: 0px;\"></div>\r\n");
            out.write("                                                                                        <div class=\"lazyload-wrapper\">\r\n");
            out.write("                                                                                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.icon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("                                                                                        </div>\r\n");
            out.write("                                                                                    </div>\r\n");
            out.write("                                                                                </div>\r\n");
            out.write("                                                                                <div class=\"MuiBox-root jss407 jss392\">\r\n");
            out.write("                                                                                    <span class=\"MuiTypography-root jss390 MuiTypography-subtitle2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.tenhang }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                                    <span class=\"MuiTypography-root jss391 MuiTypography-caption\" style=\"color: rgb(255, 51, 102);\"></span>\r\n");
            out.write("                                                                                    <span class=\"MuiTypography-root jss391 MuiTypography-caption\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.sohieu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                                </div>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                        <div class=\"MuiBox-root jss408\">\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss409 jss381\">\r\n");
            out.write("                                                                                <span class=\"MuiTypography-root jss384 MuiTypography-subtitle1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.giodi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                                <span class=\"MuiTypography-root jss383 MuiTypography-caption\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.sbdi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                            <svg width=\"40\" height=\"20\" fill=\"none\" class=\"jss393\">\r\n");
            out.write("                                                                                <g clip-path=\"url(#icon_arrow_flight_long_svg__clip0)\" stroke=\"#718096\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
            out.write("                                                                                    <path d=\"M33.5 8.5L36 11M4 11h32\"></path>\r\n");
            out.write("                                                                                </g>\r\n");
            out.write("                                                                                <defs>\r\n");
            out.write("                                                                                    <clipPath id=\"icon_arrow_flight_long_svg__clip0\">\r\n");
            out.write("                                                                                        <path fill=\"#fff\" d=\"M0 0h40v20H0z\"></path>\r\n");
            out.write("                                                                                    </clipPath>\r\n");
            out.write("                                                                                </defs>\r\n");
            out.write("                                                                            </svg>\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss410 jss382\">\r\n");
            out.write("                                                                                <span class=\"MuiTypography-root jss384 MuiTypography-subtitle1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.gioden }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                                <span class=\"MuiTypography-root jss383 MuiTypography-caption\" style=\"display: flex; justify-content: flex-end;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.sbden }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                        <div class=\"MuiBox-root jss411\">\r\n");
            out.write("                                                                            <h6 class=\"MuiTypography-root MuiTypography-subtitle2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.ngaydi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                                                            <span class=\"MuiTypography-root MuiTypography-caption\" style=\"color: rgb(74, 85, 104);\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.lotrinhbay }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                    </div>\r\n");
            out.write("                                                                    <hr class=\"MuiDivider-root jss379\">\r\n");
            out.write("                                                                    <div class=\"MuiBox-root jss412 jss380\">\r\n");
            out.write("                                                                        <div class=\"MuiBox-root jss413 jss386\">\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss414\">\r\n");
            out.write("                                                                                <span class=\"MuiTypography-root MuiTypography-caption\">Phổ Thông</span>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                        <div class=\"MuiBox-root jss415\">\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss418\" title=\"Hành lý xách tay 7kg. Hành lý ký gửi 0 kiện (0kg/kiện)\">\r\n");
            out.write("                                                                                <div class=\"MuiChip-root\" style=\"margin-right: 16px; background-color: rgb(242, 246, 249);\">\r\n");
            out.write("                                                                                    <svg width=\"16\" height=\"16\" fill=\"none\" class=\"MuiChip-icon svgFillAll\" style=\"width: 20px; stroke: rgb(74, 85, 104); height: 20px;\">\r\n");
            out.write("                                                                                        <path d=\"M3.907 13.736v.93M12.59 13.736v.93M6.388 10.015h3.72\" stroke=\"#1A202C\" stroke-miterlimit=\"10\" stroke-linecap=\"round\"></path>\r\n");
            out.write("                                                                                        <path d=\"M13.83 11.736a2 2 0 01-2 2H4.667a2 2 0 01-2-2V5.054c0-.682.558-1.24 1.24-1.24h8.682c.683 0 1.24.558 1.24 1.24v6.682zM10.109 3.814v-1.48a1 1 0 00-1-1H7.388a1 1 0 00-1 1v1.48M2.667 7.535H13.83\" stroke=\"#1A202C\" stroke-miterlimit=\"10\" stroke-linecap=\"square\"></path>\r\n");
            out.write("                                                                                    </svg>\r\n");
            out.write("                                                                                    <span class=\"MuiChip-label\">\r\n");
            out.write("                                                                                        <span class=\"MuiTypography-root MuiTypography-caption\" style=\"height: 16px;\">7 kg</span>\r\n");
            out.write("                                                                                    </span>\r\n");
            out.write("                                                                                </div>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                            <div class=\"MuiButtonBase-root MuiChip-root MuiChip-clickable\" tabindex=\"0\" role=\"button\" style=\"margin-right: 16px; height: 32px; background-color: rgb(242, 246, 249); color: rgb(26, 32, 44);\">\r\n");
            out.write("                                                                                <svg width=\"16\" height=\"16\" fill=\"none\" class=\"MuiChip-icon svgFillAll\" style=\"width: auto; stroke: rgb(74, 85, 104);\">\r\n");
            out.write("                                                                                    <path d=\"M8 14A6 6 0 108 2a6 6 0 000 12zM8 5.333h.007\" stroke=\"#1A202C\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\r\n");
            out.write("                                                                                    <path d=\"M7.333 8H8v2.667h.666\" stroke=\"#1A202C\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\r\n");
            out.write("                                                                                </svg>\r\n");
            out.write("                                                                                <span class=\"MuiChip-label\">\r\n");
            out.write("                                                                                        <span class=\"MuiTypography-root MuiTypography-caption\" style=\"height: 16px;\">Chi tiết</span>\r\n");
            out.write("                                                                                </span>\r\n");
            out.write("                                                                                <span class=\"MuiTouchRipple-root\"></span>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                        <div class=\"MuiBox-root jss419\">\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss420 jss398\">\r\n");
            out.write("                                                                                <div class=\"jss291 jss388\">\r\n");
            out.write("                                                                                    <div class=\"jss292 jss295\" style=\"border-radius: 0px;\"></div>\r\n");
            out.write("                                                                                    <div class=\"lazyload-wrapper\">\r\n");
            out.write("                                                                                        <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.icon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"jss294 jss388\" alt=\"\">\r\n");
            out.write("                                                                                    </div>\r\n");
            out.write("                                                                                </div>\r\n");
            out.write("                                                                                <p class=\"MuiTypography-root MuiTypography-body2\">Giá rẻ nhất</p>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                            <div class=\"MuiBox-root jss421\">\r\n");
            out.write("                                                                                <div class=\"MuiBox-root jss422\">\r\n");
            out.write("                                                                                   \r\n");
            out.write("                                                                                    <h6 class=\"MuiTypography-root jss395 MuiTypography-subtitle1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.giave }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                                                                </div>\r\n");
            out.write("                                                                                <button class=\"MuiButtonBase-root MuiButton-containedSecondary MuiButton-root MuiButton-text jss423 jss424 jss378\" tabindex=\"0\" type=\"submit\">\r\n");
            out.write("                                                                                    <span class=\"MuiButton-label\">\r\n");
            out.write("                                                                                        <div class=\"MuiBox-root jss425\">\r\n");
            out.write("                                                                                           <a class=\"MuiBox-root jss426\" opacity=\"1\"  href=\"datvecontrol?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.macb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Chọn</a>\r\n");
            out.write("                                                                                        </div>\r\n");
            out.write("                                                                                    </span>\r\n");
            out.write("                                                                                    <span class=\"MuiTouchRipple-root\"></span>\r\n");
            out.write("                                                                                </button>\r\n");
            out.write("                                                                            </div>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                    </div>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                            </div>\r\n");
            out.write("                                                        </div> \r\n");
            out.write("                                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
