/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-29 16:07:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <meta name=\"Description\" content=\"Enter your description here\" />\r\n");
      out.write("  <title>LUD Airline</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- bootstrap CDN -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"> \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- OWN CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"CSS/footercss.css\"> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"footer-section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"footer-cta py-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-6 col-xl-4 mb-30\">\r\n");
      out.write("            <div class=\"single-cta\">\r\n");
      out.write("              <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("              <div class=\"cta-text\">\r\n");
      out.write("                <h4>Find us</h4>\r\n");
      out.write("                <span>số 1 Lý Thường Kiệt , Phường 9,Quận Tân Bình,TP.HCM</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-6 col-xl-4 mb-30\">\r\n");
      out.write("            <div class=\"single-cta\">\r\n");
      out.write("              <i class=\"fas fa-phone\"></i>\r\n");
      out.write("              <div class=\"cta-text\">\r\n");
      out.write("                <h4>Call us</h4>\r\n");
      out.write("                <span>99999-55555</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-6 col-xl-4 mb-30\">\r\n");
      out.write("            <div class=\"single-cta\">\r\n");
      out.write("              <i class=\"fas fa-envelope-open\"></i>\r\n");
      out.write("              <div class=\"cta-text\">\r\n");
      out.write("                <h4>Mail us</h4>\r\n");
      out.write("                <span>ludtickets@gmail.com</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"footer-content py-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"footer-widget\">\r\n");
      out.write("              <div class=\"footer-logo\">\r\n");
      out.write("                <i class=\"fa-solid fa-paper-plane\"><p>LUD Airline</p></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"footer-text\">\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consec tetur adipisicing elit, sed do eiusmod tempor incididuntut consec tetur adipisicing elit,Lorem ipsum dolor sit amet.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"footer-social-icon\">\r\n");
      out.write("                <span>Follow us</span>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f facebook-bg\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter twitter-bg\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram instagram-bg\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"footer-widget\">\r\n");
      out.write("               <div class=\"footer-widget-heading\">\r\n");
      out.write("                 <h3>Useful Links</h3>\r\n");
      out.write("               </div>\r\n");
      out.write("               <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">about</a></li>\r\n");
      out.write("                <li><a href=\"#\">services</a></li>\r\n");
      out.write("                <li><a href=\"#\">portfolio</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                <li><a href=\"#\">About us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Our Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Expert Team</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Latest News</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"footer-widget\">\r\n");
      out.write("               <div class=\"footer-widget-heading\">\r\n");
      out.write("                 <h3>Subscribe</h3>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"footer-text\">\r\n");
      out.write("                  <p>Don’t miss to subscribe to our new feeds, kindly fill the form below.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"subscribe-form\">\r\n");
      out.write("                \r\n");
      out.write("                    <input type=\"text\" placeholder=\"Email Address\">\r\n");
      out.write("                    <button><i class=\"fab fa-telegram-plane\"></i></button>\r\n");
      out.write("                 \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"copyright-area\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-xl-6 col-lg-6 text-center text-lg-left\">\r\n");
      out.write("            <div class=\"copyright-text\">\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-xl-6 col-lg-6 text-right d-none d-lg-block\">\r\n");
      out.write("            <div class=\"footer-menu\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"\">Home</a></li>\r\n");
      out.write("                <li><a href=\"\">Terms</a></li>\r\n");
      out.write("                <li><a href=\"\">Privacy</a></li>\r\n");
      out.write("                <li><a href=\"\">Policy</a></li>\r\n");
      out.write("                <li><a href=\"\">Contact</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
