/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-29 16:03:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1652317442487L));
    _jspx_dependants.put("jar:file:/D:/eclipse/vemaybay/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/vemaybay/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LUDAirLine</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/main1.css\">\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("var num;\r\n");
      out.write("var temp=0;\r\n");
      out.write("var speed=5000; /* this is set for 5 seconds, edit value to suit requirements */\r\n");
      out.write("var preloads=[];\r\n");
      out.write("/* add any number of images here */\r\n");
      out.write("preload(\r\n");
      out.write("'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/banner1920x960vn1657607872-1657775978974.png',\r\n");
      out.write("'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/top-banner1920x960-copy-1659847056288.jpeg',\r\n");
      out.write("'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/website-moi1920x960-1659846765102.jpg',\r\n");
      out.write("'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/baolapc-1653912065356.jpeg'\r\n");
      out.write(");\r\n");
      out.write("function preload(){\r\n");
      out.write("for(var c=0;c<arguments.length;c++) {\r\n");
      out.write("preloads[preloads.length]=new Image();\r\n");
      out.write("preloads[preloads.length-1].src=arguments[c];\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function rotateImages() {\r\n");
      out.write("num=Math.floor(Math.random()*preloads.length);\r\n");
      out.write("if(num==temp){\r\n");
      out.write("rotateImages();\r\n");
      out.write("}\r\n");
      out.write("else{\r\n");
      out.write("document.body.style.backgroundImage='url('+preloads[num].src+')';\r\n");
      out.write("temp=num;\r\n");
      out.write("setTimeout(function(){rotateImages()},speed);\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if(window.addEventListener){\r\n");
      out.write("window.addEventListener('load',function(){setTimeout(function(){rotateImages()},speed)},false);\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("if(window.attachEvent){\r\n");
      out.write("window.attachEvent('onload',function(){setTimeout(function(){rotateImages()},speed)});\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("    <div class=\"jss3820\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header-body\">\r\n");
      out.write("                <div class=\"body-items\">\r\n");
      out.write("                    <a class=\"header-body-logo\" href=\"index.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-paper-plane\">LUD TICKETS</i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"header-body-items\" >\r\n");
      out.write("                        <div class=\"header-body-items1\">\r\n");
      out.write("                            <svg width=\"15\" heigth=\"15\" viewbox=\"0 0 15 15\" fill=\"none\" class=\"item\"></svg>\r\n");
      out.write("                             ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <span class=\"span1\">|</span>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"header-body-items2\">\r\n");
      out.write("                            <ul class=\"items\">\r\n");
      out.write("                             ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <li class=\"item1\">\r\n");
      out.write("                                <a href=\"\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"jss2636\">Check in online</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>            \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                          ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("                    </div> \r\n");
      out.write("                </div> \r\n");
      out.write("            </div>                     \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(63,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                \r\n");
          out.write("                                <span class=\"span1\">\r\n");
          out.write("                                    <a class=\"login\" href=\"dangky.jsp\">Đăng ký</a>\r\n");
          out.write("                                </span>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(70,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <span class=\"span1\">\r\n");
          out.write("                                \r\n");
          out.write("                                    <a class=\"login\" href=\"login.jsp\">Đăng nhập</a>\r\n");
          out.write("                                    </span>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /index.jsp(76,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <span class=\"span1\">\r\n");
          out.write("                                \r\n");
          out.write("                                    <a class=\"login\" href=\"dangxuatcontrol\">Đăng xuất</a>\r\n");
          out.write("                                    </span>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /index.jsp(85,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"item1\">\r\n");
          out.write("                                <a href=\"vemaybaycontrol1?sdt=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.sdt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"jss2636\">Chuyến bay của tôi</a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /index.jsp(99,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"container-430\">\r\n");
          out.write("            <div class=\"jss763\">\r\n");
          out.write("                <div class=\"jss122 jss764\">\r\n");
          out.write("                    <div class=\"jss765\">\r\n");
          out.write("                        <div class=\"jss772\">\r\n");
          out.write("                            <button class=\"MuiButtonBase-root MuiButton-root MuiButton-text\" tabindex=\"0\" type=\"button\">\r\n");
          out.write("                                <span class=\"MuiButton-label\">\r\n");
          out.write("                                    <a href=\"\" style=\"color: inherit;\">Mua hành lý, suất ăn, chọn chỗ ngồi và hơn thế nữa...</a></span>\r\n");
          out.write("                                <span class=\"MuiTouchRipple-root\"></span>\r\n");
          out.write("                            </button>\r\n");
          out.write("                            <button class=\"MuiButtonBase-root MuiButton-root MuiButton-text\" tabindex=\"0\" type=\"button\">\r\n");
          out.write("                                <span class=\"MuiButton-label\">\r\n");
          out.write("                                    <a href=\"\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"display: block; width: 100%; height: 100%; text-decoration: none; color: white;\">Gửi hàng nhanh</a></span>\r\n");
          out.write("                                <span class=\"MuiTouchRipple-root\"></span>\r\n");
          out.write("                            </button>\r\n");
          out.write("                        </div>\r\n");
          out.write("                        <form action=\"Searchcontrol\" method=\"get\">\r\n");
          out.write("                        <div class=\"jss771\">\r\n");
          out.write("                            \r\n");
          out.write("                            <div class=\"jss778\">\r\n");
          out.write("                                <div class=\"jss781\">\r\n");
          out.write("                                    <div class=\"jss555\">\r\n");
          out.write("                                        <svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\">\r\n");
          out.write("                                            <path d=\"M6 19.5456L8 19.5456L13 11.4172L18.5 11.4172C18.8978 11.4172 19.2794 11.2566 19.5607 10.9708C19.842 10.685 20 10.2974 20 9.89314C20 9.48894 19.842 9.10128 19.5607 8.81546C19.2794 8.52965 18.8978 8.36908 18.5 8.36908L13 8.36908L8 0.240722L6 0.240722L8.5 8.36908L3 8.36908L1.5 6.33699L-2.62268e-07 6.33699L1 9.89314L-5.68248e-07 13.4493L1.5 13.4493L3 11.4172L8.5 11.4172L6 19.5456Z\" fill=\"#333333\"></path>\r\n");
          out.write("                                        </svg>\r\n");
          out.write("                                        \r\n");
          out.write("                                        <div class=\"MuiFormControl-root MuiTextField-root jss557 MuiFormControl-fullWidth\">\r\n");
          out.write("                                            \r\n");
          out.write("                                            <div class=\"MuiInputBase-root MuiOutlinedInput-root MuiInputBase-fullWidth MuiInputBase-formControl\">\r\n");
          out.write("                                                <div class=\"select\">\r\n");
          out.write("                                                    <select name=\"sbdi\" style=\"\r\n");
          out.write("                                                    height: 40px;\r\n");
          out.write("                                                    width: 165px;\r\n");
          out.write("                                                    margin: 4px 4px 4px 40px;\r\n");
          out.write("                                                    font-size: larger;\r\n");
          out.write("                                                    font-weight: 700;\r\n");
          out.write("                                                \">\r\n");
          out.write("                                                \r\n");
          out.write("                                                      <option selected disabled>Điểm khởi hành</option>\r\n");
          out.write("                                                      \r\n");
          out.write("                                                       <option value=\"SGN\">TP.Hồ Chí Minh</option>\r\n");
          out.write("                                                      <option value=\"HAN\">Hà Nội</option>\r\n");
          out.write("                                                      <option value=\"BMV\">Buôn Ma Thuột</option>\r\n");
          out.write("                                                      <option value=\"VCA\">Cần Thơ</option>\r\n");
          out.write("                                                      <option value=\"DAD\">Đà Nẵng</option>\r\n");
          out.write("                                                      <option value=\"DLI\">Đà Lạt</option>\r\n");
          out.write("                                                      <option value=\"VII\">TP.Vinh</option>\r\n");
          out.write("                                                      <option value=\"PQC\">Kiên Giang</option>\r\n");
          out.write("                                                      <option value=\"CXR\">Nha Trang</option>\r\n");
          out.write("                                                      <option value=\"UIH\">Quy Nhơn</option>\r\n");
          out.write("                                                      <option value=\"VCS\">Bà Rịa-Vũng Tàu</option>\r\n");
          out.write("                                                      <option value=\"HUI\">Huế</option>\r\n");
          out.write("                                                      <option value=\"VDH\">Quảng Bình</option>\r\n");
          out.write("                                                      <option value=\"TBB\">Phú Yên</option>\r\n");
          out.write("                                                      <option value=\"HPH\">Hải Phòng</option>\r\n");
          out.write("                                                    </select>\r\n");
          out.write("                                                  </div> \r\n");
          out.write("                                                \r\n");
          out.write("                                            </div>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"jss625\" role=\"button\" tabindex=\"0\" style=\"flex-wrap: wrap;\">\r\n");
          out.write("                                        <div class=\"jss626\">\r\n");
          out.write("                                            <p class=\"MuiTypography-root jss137 MuiTypography-h3 MuiTypography-colorTextPrimary\" weight=\"Medium\">Ngày đi</p>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                        <div>\r\n");
          out.write("                                        <input type=\"date\" name = \"ngaydi\" />\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    \r\n");
          out.write("                                    </div></div>    \r\n");
          out.write("                                <div class=\"jss781\">\r\n");
          out.write("                                    <div class=\"jss555\">\r\n");
          out.write("                                        <svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\">\r\n");
          out.write("                                        <path d=\"M14 0.267883L12 0.267883L7 8.39625L1.5 8.39625C1.10218 8.39625 0.720645 8.55682 0.43934 8.84264C0.158035 9.12846 1.1803e-07 9.51611 1.13286e-07 9.92032C1.08542e-07 10.3245 0.158035 10.7122 0.43934 10.998C0.720645 11.2838 1.10218 11.4444 1.5 11.4444L7 11.4444L12 19.5728L14 19.5728L11.5 11.4444L17 11.4444L18.5 13.4765L20 13.4765L19 9.92032L20 6.36416L18.5 6.36416L17 8.39625L11.5 8.39625L14 0.267883Z\" fill=\"#333333\"></path>\r\n");
          out.write("                                        </svg>\r\n");
          out.write("                                        <div class=\"MuiFormControl-root MuiTextField-root jss557 MuiFormControl-fullWidth\">\r\n");
          out.write("                                            \r\n");
          out.write("                                            <div class=\"MuiInputBase-root MuiOutlinedInput-root MuiInputBase-fullWidth MuiInputBase-formControl\">\r\n");
          out.write("                                                <div class=\"select\">\r\n");
          out.write("                                                    <select  name=\"sbden\" style=\"\r\n");
          out.write("                                                    height: 40px;\r\n");
          out.write("                                                    width: 290px;\r\n");
          out.write("                                                    margin: 4px 4px 4px 40px;\r\n");
          out.write("                                                    font-size: larger;\r\n");
          out.write("                                                    font-weight: 700;\r\n");
          out.write("                                                     \">\r\n");
          out.write("                                                      <option selected disabled>Điểm đến</option>\r\n");
          out.write("                                                      <option value=\"SGN\">TP.Hồ Chí Minh</option>\r\n");
          out.write("                                                      <option value=\"HAN\">Hà Nội</option>\r\n");
          out.write("                                                      <option value=\"BMV\">Buôn Ma Thuột</option>\r\n");
          out.write("                                                      <option value=\"VCA\">Cần Thơ</option>\r\n");
          out.write("                                                      <option value=\"DAD\">Đà Nẵng</option>\r\n");
          out.write("                                                      <option value=\"DLI\">Đà Lạt</option>\r\n");
          out.write("                                                      <option value=\"VII\">TP.Vinh</option>\r\n");
          out.write("                                                      <option value=\"PQC\">Kiêng Giang</option>\r\n");
          out.write("                                                      <option value=\"CXR\">Nha Trang</option>\r\n");
          out.write("                                                      <option value=\"UIH\">Bình Định</option>\r\n");
          out.write("                                                      <option value=\"VCS\">Bà Rịa-Vũng Tàu</option>\r\n");
          out.write("                                                      <option value=\"HUI\">Huế</option>\r\n");
          out.write("                                                      <option value=\"VDH\">Quảng Bình</option>\r\n");
          out.write("                                                      <option value=\"TBB\">Phú Yên</option>\r\n");
          out.write("                                                      <option value=\"HPH\">Hải Phòng</option>\r\n");
          out.write("                                                    </select>\r\n");
          out.write("                                                  </div>\r\n");
          out.write("                                                  </div>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    </div>                       \r\n");
          out.write("                                </div>\r\n");
          out.write("                                <div class=\"MuiFormControl-root jss797\">\r\n");
          out.write("                                    <label class=\"MuiFormLabel-root MuiInputLabel-root jss801 MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiFormLabel-filled\" data-shrink=\"true\" for=\"input-base-custom-6\">Hành khách</label>\r\n");
          out.write("                                    <div class=\"MuiInputBase-root jss802 MuiInputBase-formControl MuiInputBase-adornedStart MuiInputBase-adornedEnd\">\r\n");
          out.write("                                        <div class=\"MuiInputAdornment-root MuiInputAdornment-positionEnd\">\r\n");
          out.write("                                            <svg width=\"17\" height=\"17\" viewBox=\"0 0 17 17\" fill=\"none\">\r\n");
          out.write("                                                <path d=\"M8.5 0C9.62717 0 10.7082 0.447766 11.5052 1.2448C12.3022 2.04183 12.75 3.12283 12.75 4.25C12.75 5.37717 12.3022 6.45817 11.5052 7.2552C10.7082 8.05223 9.62717 8.5 8.5 8.5C7.37283 8.5 6.29183 8.05223 5.4948 7.2552C4.69777 6.45817 4.25 5.37717 4.25 4.25C4.25 3.12283 4.69777 2.04183 5.4948 1.2448C6.29183 0.447766 7.37283 0 8.5 0ZM8.5 10.625C13.1962 10.625 17 12.5269 17 14.875V17H0V14.875C0 12.5269 3.80375 10.625 8.5 10.625Z\" fill=\"#333333\"></path>\r\n");
          out.write("                                            </svg>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                        <input aria-invalid=\"false\" id=\"input-base-custom-6\" readonly=\"\" type=\"text\" class=\"MuiInputBase-input jss803 MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd\" value=\"1 người lớn\">\r\n");
          out.write("                                        <div class=\"MuiInputAdornment-root MuiInputAdornment-positionEnd\">\r\n");
          out.write("                                            <svg width=\"24\" xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\">                                                    <path d=\"M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z\"></path>\r\n");
          out.write("                                               <path fill=\"none\" d=\"M0 0h24v24H0V0z\"></path>\r\n");
          out.write("                                            </svg>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                </div>                               \r\n");
          out.write("                            </div> \r\n");
          out.write("                            <div class=\"jss782\">\r\n");
          out.write("                                    <button class=\"MuiButtonBase-root MuiButton-root MuiButton-contained\" tabindex=\"0\" type=\"submit\">\r\n");
          out.write("                                        <a  class=\"MuiButton-label\" >Tìm chuyến bay</a>\r\n");
          out.write("                                        <span class=\"MuiTouchRipple-root\"></span>\r\n");
          out.write("                                    </button>\r\n");
          out.write("                            </div>   \r\n");
          out.write("                        </div> \r\n");
          out.write("                        </form>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /index.jsp(235,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \r\n");
          out.write("                         <div class=\"jss2001\">\r\n");
          out.write("                                    <button>\r\n");
          out.write("                                        <a  class=\"MuiButton-label\" >Hãy đăng nhập để sử dụng dịch vụ của LUD tickets bạn nhé!</a>\r\n");
          out.write("                                        <span class=\"MuiTouchRipple-root\"></span>\r\n");
          out.write("                                    </button>\r\n");
          out.write("                            </div>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
