/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-29 16:03:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Trang đăng nhập</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap');\r\n");
      out.write(" *{\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   box-sizing: border-box;\r\n");
      out.write("   font-family: 'Roboto', sans-serif;\r\n");
      out.write(" }\r\n");
      out.write(" html,body{\r\n");
      out.write("   display: grid;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   place-items: center;\r\n");
      out.write("  background-color: #FBAB7E;\r\n");
      out.write(" background-image: linear-gradient(62deg, #FBAB7E 0%, #F7CE68 100%);\r\n");
      out.write(" }\r\n");
      out.write(" .container{\r\n");
      out.write("   position: relative;\r\n");
      out.write("   height: 55px;\r\n");
      out.write("   width: 320px;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   box-shadow: 0px 3px 3px rgba(0,0,0,0.1);\r\n");
      out.write(" }\r\n");
      out.write(" .container input{\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   border: 1px solid #8e44ad;\r\n");
      out.write("   padding-left: 15px;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("   outline: none;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write(" }\r\n");
      out.write(" .container input::placeholder{\r\n");
      out.write("   font-size: 17px;\r\n");
      out.write(" }\r\n");
      out.write(" .container span{\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   right: 15px;\r\n");
      out.write("   top: 50%;\r\n");
      out.write("   transform: translateY(-50%);\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   color: #8e44ad;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   display: none;\r\n");
      out.write(" }\r\n");
      out.write(" .container input:valid ~ span{\r\n");
      out.write("   display: block;\r\n");
      out.write(" }\r\n");
      out.write(" .container span i.hide-btn::before{\r\n");
      out.write("   content: \"f070\";\r\n");
      out.write(" }\r\n");
      out.write(".login-form {\r\n");
      out.write("    width: 340px;\r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("  	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".login-form form {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    background: #f7f7f7;\r\n");
      out.write("    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("}\r\n");
      out.write(".login-form h2 {\r\n");
      out.write("    margin: 0 0 15px;\r\n");
      out.write("}\r\n");
      out.write(".form-control, .btn {\r\n");
      out.write("    min-height: 38px;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write(".btn {        \r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<a class=\"header-body-logo\" href=\"index.jsp\" style=\"color:#f00; font-size:50px\">\r\n");
      out.write("                        <i class=\"fa-solid fa-paper-plane\">LUD TICKETS</i>\r\n");
      out.write("                    </a>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"login-form\">\r\n");
      out.write("    <form action=\"logincontrol\" method=\"post\">\r\n");
      out.write("    \r\n");
      out.write("        <h2 class=\"text-center\">Đăng nhập</h2>       \r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("          <p class=\"text-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("     \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <input type=\"number\" name=\"username\" class=\"form-control\" placeholder=\"số điện thoại\" required=\"required\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"password\" required=\"required\">\r\n");
      out.write("                  \r\n");
      out.write("            \r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-block\">Đăng nhập</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clearfix\">\r\n");
      out.write("           \r\n");
      out.write("        </div>        \r\n");
      out.write("    </form>\r\n");
      out.write("    <p class=\"text-center\"><a href=\"dangky.jsp\">Tạo tài khoản mới</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("const passField = document.querySelector(\"input\");\r\n");
      out.write("const showBtn = document.querySelector(\"span i\");\r\n");
      out.write("showBtn.onclick = (()=>{\r\n");
      out.write("  if(passField.type === \"password\"){\r\n");
      out.write("    passField.type = \"text\";\r\n");
      out.write("    showBtn.classList.add(\"hide-btn\");\r\n");
      out.write("  }else{\r\n");
      out.write("    passField.type = \"password\";\r\n");
      out.write("    showBtn.classList.remove(\"hide-btn\");\r\n");
      out.write("  }\r\n");
      out.write("});</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
